project:
  type: book
  output-dir: _book

book:
  title: "MA22019 Introduction to Data Science - Lecture Notes"
  author: "Dr Christian Rohrbeck"
  date: "February 2025"
  chapters:
    - index.qmd

    - 01-DataWrangling.qmd
    - 02-DataVisualization.qmd
    - 03-Text-Data-Analysis.qmd
    - 04-SpatialDataAnalysis.qmd
  
bibliography: 
  - book.bib
  - packages.bib

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
  
