project:
  type: website

website:
  title: "MA22019"
  description: "Spatial Statistics at University of Dundee"
  page-navigation: true

  sidebar:
    background: "#005871"
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
      - section: "Computing"
        contents:
          - href: computing-setup/project-structure.qmd
            text: Project Structure
          - href: computing-setup/setup-university-drive.qmd
            text: University Drive Setup
          - href: computing-setup/computing-assignments.qmd
            text: Assignments Workflow
          - href: computing-setup/why-quarto.qmd
            text: Why Quarto?
      - section: "Lecture Notes"
        contents:
          - href: MA22019 Lecture Notes/index.qmd
            text: Introduction
          - MA22019 Lecture Notes/01-DataWrangling.qmd
          - MA22019 Lecture Notes/02-DataVisualization.qmd
          - MA22019 Lecture Notes/03-Text-Data-Analysis.qmd
          - MA22019 Lecture Notes/04-SpatialDataAnalysis.qmd
      - slides.qmd
      - labs.qmd
      - homework.qmd
      - coursework.qmd

  page-footer:
    background: "#005871"
    left: "Â© Copyright 2025, University of Dundee"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: [cosmo, style/sta199.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-light
    toc: true
    code-copy: hover
    code-link: true

execute:
  freeze: auto
