project:
  type: website

website:
  title: "MA22019"
  description: "Spatial Statistics at University of Dundee"
  navbar:
    background: "#005871"
    left:
      - href: index.qmd
        text: Home
      - href: computing-setup.qmd
        text: Computing
      - href: MA22019 Lecture Notes/index.qmd
        text: Lecture Notes
      - href: slides.qmd
        text: Slides
      - href: labs.qmd
        text: Labs
      - href: homework.qmd
        text: Homework & Quizzes
      - href: coursework.qmd
        text: Coursework
    right:
      - icon: github
        href: https://github.com/kanayai/ma22019_website
        text: GitHub
    sidebar:
      - title: "Lecture Notes"
        style: docked
        search: true
        collapse-level: 1
        contents:
          - href: MA22019 Lecture Notes/index.qmd
            text: Introduction
          - MA22019 Lecture Notes/01-DataWrangling.qmd
          - MA22019 Lecture Notes/02-DataVisualization.qmd
          - MA22019 Lecture Notes/03-Text-Data-Analysis.qmd
          - MA22019 Lecture Notes/04-SpatialDataAnalysis.qmd

format:
  html:
    theme: [cosmo, style/sta199.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-light
    toc: true
    code-copy: hover
    code-link: true

execute:
  freeze: auto
