project:
  type: website

website:
  title: "MA22019"
  description: "Introduction to Data Science at the University of Bath"
  page-navigation: true

  sidebar:
    background: "#005871"
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
      - section: "Computing"
        contents:
          - href: computing_setup/project_structure.qmd
            text: Project Structure
          - href: computing_setup/setup_university_drive.qmd
            text: University Drive Setup
          - href: computing_setup/computing_assignments.qmd
            text: Assignments Workflow
          - href: computing_setup/why_quarto.qmd
            text: Why Quarto?
      - section: "Lecture Notes"
        contents:
          - href: lecture_notes/index.qmd
            text: Introduction
          - lecture_notes/01-DataWrangling.qmd
          - lecture_notes/02-DataVisualization.qmd
          - lecture_notes/03-Text-Data-Analysis.qmd
          - lecture_notes/04-SpatialDataAnalysis.qmd
      - slides.qmd
      - case_studies.qmd
      - labs.qmd
      - homework.qmd
      - coursework.qmd

  page-footer:
    background: "#005871"
    left: "Â© Copyright 2025, University of Bath"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: [cosmo, style/sta199.scss]
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-light
    toc: true
    code-copy: hover
    code-link: true

execute:
  freeze: auto
