format:
  revealjs:
    theme: slides.scss
    transition: fade
    slide-number: true
    toc: false
    code-link: true
    footer: "[ðŸ”— MA22019 Website](https://github.com/kanayai/ma22019_website)"
    # logo: "images/logo.png" # Uncomment when logo is available
